version: '3'

services:
  database:
    image: postgres:12-alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: new_password
      POSTGRES_USER: root
      POSTGRES_DB: crawlspace

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: shashank@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./.data/pgadmin:/root/.pgadmin
